language: php

php:
  - 7.2
  - 7.3
  - 7.4

before_script:
  - travis_retry composer install --prefer-source --no-interaction --dev

script:
  - vendor/bin/php-cs-fixer fix src --dry-run --rules=@PSR2
  - vendor/bin/phpspec run --no-interaction --verbose

after_success:
  - bash <(curl -s https://codecov.io/bash)
